### ISSUE TITLE
typo issue

### ISSUE THREAD

**Issue by ahmadalli** [gree-gorey/passbolt#1]
https://github.com/gree-gorey/passbolt/blob/14e2a91aa9f827495a43b0bffff721b78b73e4c0/templates/passbolt-statefulset.yaml#L70-L75

you've misspelled `certificate` :)

**Comment by gree-gorey** [comment]
Thank you!

fixed by https://github.com/gree-gorey/passbolt/commit/0e5cd7da57a47e624bed945aede27166e0676a47
