### ISSUE TITLE
version mismatch?

### ISSUE THREAD

**Issue by aars** [gree-gorey/passbolt#2]
`index.yaml` from gh-pages branch has version `version: 2.1.0` while `Chart.yaml` in master branch has `version: 2.1.0-debian`. Shouldn't these match?

**Comment by gree-gorey** [comment]
Yes, thank you for pointing this out.
I definitely mixed up app version and chart version. Fixed by https://github.com/gree-gorey/passbolt/commit/bd3b9718917d71d99368109355b125bc44af4fd4 and https://github.com/gree-gorey/passbolt/commit/c2d2825b75c6c4d5ed4811b567d4451a74908cf4
